probabilities = "./agent/probs.toml"
sharer_trust = "./agent/trust.toml"
prospect = "./agent/x[4-8_33]-ym3.csv"
cpt = "./agent/cpt.csv"
initial_states = "./agent/initial_states.toml"

condition = "./agent/condition.toml"
uncertainty = "./agent/uncertainty.toml"
