probabilities  = "../agent/probs.toml"
sharer_trust   = "../agent/trust.toml"
prospect       = "../prospect/x[4-8_33]-ym3.csv"
cpt            = "../agent/cpt.csv"
initial_states = "../agent/initial_states.toml"

[condition]
# "../cond/d95b0_d[0-20_21]u20.csv"
o_b = { generate = [
    [{b=[0,{single=0.95}]},{b=[1,{single=0.0}]}],
    [{b=[0,{uniform=[0.0,0.20]}]},{u={single=0.20}}],
] }
# "../cond/d95b0_d[10-30_21]u10.csv"
a_fh = { generate = [
    [{b=[0,{single=0.95}]},{b=[1,{single=0.0}]}],
    [{b=[0,{uniform=[0.10,0.30]}]},{u={single=0.10}}],
] }
# "../cond/d95b0_d[10-30_21]u10.csv"
b_kh = { generate = [
    [{b=[0,{single=0.95}]},{b=[1,{single=0.0}]}],
    [{b=[0,{uniform=[0.10,0.30]}]},{u={single=0.10}}],
] }
# "../cond/d95b0_d[20-40_21]u40.csv"
theta_h = { generate = [
    [{b=[0,{single=0.95}]},{b=[1,{single=0.0}]}],
    [{b=[0,{uniform=[0.20,0.40]}]},{u={single=0.40}}],
] }
# "../cond/d95b0_d[50-70_21]u10.csv"
thetad_h = { generate = [
    [{b=[0,{single=0.95}]},{b=[1,{single=0.0}]}],
    [{b=[0,{uniform=[0.50,0.70]}]},{u={single=0.10}}],

] }
# "../cond/d0b0_d[50-70_21]u25.csv"
h_psi_if_phi0 = { generate = [
    [{b=[0,{single=0.0}]},{b=[1,{single=0.0}]}],
    [{b=[0,{uniform=[0.50,0.70]}]},{u={single=0.25}}],

] }
# "../cond/d54b0_d[0-20_21]u30.csv"
h_b_if_phi0 = { generate = [
    [{b=[0,{single=0.54}]},{b=[1,{single=0.0}]}],
    [{b=[0,{uniform=[0.0,0.20]}]},{u={single=0.30}}],
] }

[uncertainty]
fh_fpsi_if_fphi0 = "../uncertainty/1d_30.csv"
kh_kpsi_if_kphi0 = "../uncertainty/1d_30.csv"
fh_fphi_fo       = "../uncertainty/2d_30_1.csv"
kh_kphi_ko       = "../uncertainty/2d_30_1.csv"
