probabilities  = "./agent/probs.toml"
sharer_trust   = "./agent/trust.toml"
# prospect       = "./prospect/x[5-7_17].csv"
prospect       = "./prospect/x[4-8_33]-ym3.csv"
# prospect       = "./prospect/x[4-6_17].csv"
cpt            = "./agent/cpt.csv"
initial_states = "./agent/initial_states.toml"

[condition]
o_b           = "./cond/d95b0_d10b70.csv"
a_fh          = "./cond/d95b0_d[10-30_21]u10.csv"
# a_fh          = "./cond/d95b0_d10u10.csv"
# b_kh          = "./cond/d95b0_d10u10.csv"
b_kh          = "./cond/d95b0_d[10-30_21]u10.csv"
# b_kh          = "./cond/d95b0_d[10-20_11]u10.csv"
# a_fh          = "./cond/d95b0_d40u10.csv"
# b_kh          = "./cond/d95b0_d40u10.csv"
theta_h       = "./cond/d95b0_d[20-40_21]u40.csv"
thetad_h       = "./cond/d95b0_d[50-70_21]u10.csv"
# thetad_h      = "./cond/d95b0_d[50-70_21]u10.csv"
# theta_h       = "./cond/d95b0_d10b50.csv"
# thetad_h      = "./cond/d95b0_d10u10.csv"
h_psi_if_phi0 = "./cond/d0b0_d80u0.csv"
h_b_if_phi0   = "./cond/d70b0_d[0-20_21]u30.csv"

# parameter for selfish by misinfo
# o_b           = "./ops/cond/95_[50-50_1].csv"
# a_fh          = "./ops/cond/95_[30-50_9].csv"
# b_kh          = "./ops/cond/95_[30-50_9].csv"
# theta_h       = "./ops/cond/95_[30-30_1].csv"
# thetad_h      = "./ops/cond/95_[80-100_9].csv"
# h_psi_if_phi0 = "./ops/cond/95_[95-95_1].csv"
# h_b_if_phi0   = "./ops/cond/95_[95-95_1].csv"

# parameter for selfish by correction?
# o_b           = "./ops/cond/95_[50-50_1].csv"
# a_fh          = "./ops/cond/95_[50-50_1].csv"
# b_kh          = "./ops/cond/95_[95-95_1].csv"
# theta_h       = "./ops/cond/95_[75-90_7].csv"
# thetad_h      = "./ops/cond/95_[75-90_7].csv"
# h_psi_if_phi0 = "./ops/cond/95_[95-95_1].csv"
# h_b_if_phi0   = "./ops/cond/95_[95-95_1].csv"

[uncertainty]
fh_fpsi_if_fphi0 = "./uncertainty/1d_30.csv"
kh_kpsi_if_kphi0 = "./uncertainty/1d_30.csv"
fh_fphi_fo       = "./uncertainty/2d_30_1.csv"
kh_kphi_ko       = "./uncertainty/2d_30_1.csv"
