informing = "./informing/case2o-m.toml"

[information]
misinfo     = "./opinion/a75_50.csv"
correction  = "./opinion/n95_95.csv"
observation = "./opinion/a75_80.csv"
inhibition  = "./inhibition/98_98.csv"
