informing = "./test/informing-test.toml"

[information]
misinfo     = "./strategy/info/a80-90_80.csv"
correction  = "./strategy/info/n95_95.csv"
observation = "./strategy/info/a100_95.csv"
inhibition  = "./strategy/info/inhibition2.csv"
