[initial_opinions]
psi  = [[0.0, 0.0], 1.0, [0.95, 0.05]]
fpsi = [[0.0, 0.0], 1.0, [0.95, 0.05]]
kpsi = [[0.0, 0.0], 1.0, [0.95, 0.05]]
phi  = [[0.0, 0.0], 1.0, [0.5, 0.5]]
fphi = [[0.0, 0.0], 1.0, [0.5, 0.5]]
kphi = [[0.0, 0.0], 1.0, [0.5, 0.5]]
o    = [[0.0, 0.0], 1.0, [0.95, 0.05]]
fo   = [[0.0, 0.0], 1.0, [0.5, 0.5]]
ko   = [[0.0, 0.0], 1.0, [0.5, 0.5]]
h_psi_if_phi1 = [
    [[0.0, 0.0], 1.0],
    [[0.0, 0.0], 1.0],
]
fh_fpsi_if_fphi1 = [
    [[0.0, 0.0], 1.0],
    [[0.0, 0.0], 1.0],
]
kh_kpsi_if_kphi1 = [
    [[0.0, 0.0], 1.0],
    [[0.0, 0.0], 1.0],
]
h_b_if_phi1 = [
    [[0.0, 0.0], 1.0],
    [[0.0, 0.0], 1.0],
]

[initial_base_rates]
a      = [0.40, 0.60]
b      = [0.60, 0.40]
h      = [0.95, 0.05]
fh     = [0.95, 0.05]
kh     = [0.95, 0.05]
theta  = [0.95, 0.05]
thetad = [0.95, 0.05]
