# "../cond/d95b0_d[0-20_21]u20.csv"
o_b = { generate = [
    [{b=[0,{single=0.95}]},{b=[1,{single=0.0}]}],
    [{b=[0,{uniform=[0.0,0.20]}]},{u={single=0.20}}],
] }
# "../cond/d95b0_d[10-30_21]u10.csv"
a_fh = { generate = [
    [{b=[0,{single=0.95}]},{b=[1,{single=0.0}]}],
    [{b=[0,{uniform=[0.10,0.30]}]},{u={single=0.10}}],
] }
# "../cond/d95b0_d[10-30_21]u10.csv"
b_kh = { generate = [
    [{b=[0,{single=0.95}]},{b=[1,{single=0.0}]}],
    [{b=[0,{uniform=[0.10,0.30]}]},{u={single=0.10}}],
] }
# "../cond/d95b0_d[20-40_21]u40.csv"
theta_h = { generate = [
    [{b=[0,{single=0.95}]},{b=[1,{single=0.0}]}],
    [{b=[0,{uniform=[0.20,0.40]}]},{u={single=0.40}}],
] }
# "../cond/d95b0_d[50-70_21]u10.csv"
thetad_h = { generate = [
    [{b=[0,{single=0.95}]},{b=[1,{single=0.0}]}],
    [{b=[0,{uniform=[0.50,0.70]}]},{u={single=0.10}}],

] }
# "../cond/d0b0_d[50-70_21]u25.csv"
h_psi_if_phi0 = { generate = [
    [{b=[0,{single=0.0}]},{b=[1,{single=0.0}]}],
    [{b=[0,{uniform=[0.50,0.70]}]},{u={single=0.25}}],

] }
# "../cond/d50b0_d[0-20_21]u30.csv"
h_b_if_phi0 = { generate = [
    [{b=[0,{single=0.50}]},{b=[1,{single=0.0}]}],
    [{b=[0,{uniform=[0.0,0.20]}]},{u={single=0.30}}],
] }
