viewing = { single = 0.5 }
viewing_friend = { single = 0.1 }
viewing_social = { single = 0.1 }
arrival_friend = { single = 0.5 }
plural_ignore_friend = { uniform = [0.0, 0.3] }
plural_ignore_social = { uniform = [0.0, 0.2] }
